task 6
Anton-Bond/ReactJS pull request #6
Opened 2020-07-12 17:28 UTC by Anton-Bond

2020-07-13 08:48 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/87284103-ae1b8d80-c4fe-11ea-916d-72e180925a7c.png)
поправьте это

2020-07-13 08:53 UTC, dima19972525 requested changes
Поправьте изменения

2020-07-13 08:53 UTC, dima19972525 commented on src/Card/CardBody/CardBody.css
> +  max-width: 100%;
можно просто width: 100%

2020-07-13 08:53 UTC, dima19972525 commented on src/App.js
> +  render() {
не пойдет
```js
...
if (checkedCardIndexes.includes(index)) {
      return null
    }
...
```
Удаляйте карточки прямо из массива this.state.planets в компоненьте App

2020-07-15 19:52 UTC, Anton-Bond commented
Не могу понять почему не обновляются state в компоненте Card после изменения state в App компоненте(удаление карточки), хотя в CardList состояние обновляется.

2020-07-20 07:19 UTC, dima19972525 commented
> Не могу понять почему не обновляются state в компоненте Card после изменения state в App компоненте(удаление карточки), хотя в CardList состояние обновляется.

сейчас гляну (был в отпуске)

2020-07-20 07:29 UTC, dima19972525 commented
Не могу точно протестировать вашу проблему (пришлите мне шаги, как это сделать), но предполагаю, что ошибка в следующем:
Скорее всего ошибка в том, что state инициализируется 1 раз
![image](https://user-images.githubusercontent.com/23092460/87910485-c6495a80-ca72-11ea-8e73-1077b5dda9e5.png)
Когда вы шлете новые пропсы title\context, ваш стейт не обновляется.

Вы можете попробовать отказаться от стейта cardValues и выставлять значения карточки прямо из пропсов, либо обновите стейт в методе getDerivedStateFromProps

2020-07-20 19:13 UTC, Anton-Bond commented
Проблема была в том, что когда выделяешь карточки и нажимаешь удалить, то удалялись последние количеством равным количеству выбранных (а не именно выбранные). Получилось реализовать через изменение state в методе getDerivedStateFromProps

2020-07-21 08:03 UTC, dima19972525 commented
Обычно, мы получаем такие структуры как массив данных с бэка, и эти данные должны содержать id. С id легче работать и он немного ускоряет работу (например, в пропс key будет передаваться уникальное значение, а не переменьчивый index)

Код
```js
saveHandler = (index) => (value) => {
    this.setState({
      planets: this.state.planets.map((planet, _index) => {
        return index === _index ? { ...value } : planet;
      }),
    });
  };
```
Поменяется на 
```js
saveHandler = (id) => (value) => {
    this.setState({
      planets: this.state.planets.map((planet) => {
        return id  === planet.id? { ...value } : planet;
      }),
    });
  };
```
(что не влияет на перформанс, но при работе с реальными данными, такие функции выглядят именно так)

Для генерации id, можете использовать пакет https://www.npmjs.com/package/uuid

2020-07-21 08:04 UTC, dima19972525 approved these changes
Поправьте изменения и мерж

2020-07-21 18:57 UTC, merged